document.querySelector(".firstt").addEventListener("mouseover",function(){
    gsap.to(".first>h4:nth-child(1)",{
        y:"-40"
    })
    gsap.to(".first>h4:nth-child(2)",{
        y:"-35"
    })
})
document.querySelector(".firstt").addEventListener("mouseout",function(){
    gsap.to(".first>h4:nth-child(1)",{
        y:"0"
    })
    gsap.to(".first>h4:nth-child(2)",{
        y:"0"
    })
})

document.querySelector(".secc").addEventListener("mouseover",function(){
    gsap.to(".sec>h4:nth-child(1)",{
        y:"-40"
    })
    gsap.to(".sec>h4:nth-child(2)",{
        y:"-35"
    })
})
document.querySelector(".secc").addEventListener("mouseout",function(){
    gsap.to(".sec>h4:nth-child(1)",{
        y:"0"
    })
    gsap.to(".sec>h4:nth-child(2)",{
        y:"0"
    })
})
document.querySelector(".thirdd").addEventListener("mouseover",function(){
    gsap.to(".third>h4:nth-child(1)",{
        y:"-40"
    })
    gsap.to(".third>h4:nth-child(2)",{
        y:"-35"
    })
})
document.querySelector(".thirdd").addEventListener("mouseout",function(){
    gsap.to(".third>h4:nth-child(1)",{
        y:"0"
    })
    gsap.to(".third>h4:nth-child(2)",{
        y:"0"
    })
})
document.querySelector(".fourthh").addEventListener("mouseover",function(){
    gsap.to(".fourth>h4:nth-child(1)",{
        y:"-40"
    })
    gsap.to(".fourth>h4:nth-child(2)",{
        y:"-35"
    })
})
document.querySelector(".fourthh").addEventListener("mouseout",function(){
    gsap.to(".fourth>h4:nth-child(1)",{
        y:"0"
    })
    gsap.to(".fourth>h4:nth-child(2)",{
        y:"0"
    })
})
document.querySelector(".fifthh").addEventListener("mouseover",function(){
    gsap.to(".fifth>h4:nth-child(1)",{
        y:"-40"
    })
    gsap.to(".fifth>h4:nth-child(2)",{
        y:"-35"
    })
})
document.querySelector(".fifthh").addEventListener("mouseout",function(){
    gsap.to(".fifth>h4:nth-child(1)",{
        y:"0"
    })
    gsap.to(".fifth>h4:nth-child(2)",{
        y:"0"
    })
})
document.querySelector(".sixthh").addEventListener("mouseover",function(){
    gsap.to(".sixth>h4:nth-child(1)",{
        y:"-40"
    })
    gsap.to(".sixth>h4:nth-child(2)",{
        y:"-35"
    })
})
document.querySelector(".sixthh").addEventListener("mouseout",function(){
    gsap.to(".sixth>h4:nth-child(1)",{
        y:"0"
    })
    gsap.to(".sixth>h4:nth-child(2)",{
        y:"0"
    })
})
document.querySelector(".sevenn").addEventListener("mouseover",function(){
    gsap.to(".seven>h4:nth-child(1)",{
        y:"-40"
    })
    gsap.to(".seven>h4:nth-child(2)",{
        y:"-35"
    })
})
document.querySelector(".sevenn").addEventListener("mouseout",function(){
    gsap.to(".seven>h4:nth-child(1)",{
        y:"0"
    })
    gsap.to(".seven>h4:nth-child(2)",{
        y:"0"
    })
})

gsap.to(".slide1",{
    scrollTrigger:{
        scroll:"body",
        trigger:"#first",
        // markers:true,
        start:"top 20%",
        end:"bottom 10%",
        scrub:true

    },
    x:"-200",
})
gsap.to(".slide2",{
    scrollTrigger:{
        scroll:"body",
        trigger:"#first",
        // markers:true,
        start:"top 20%",
        end:"bottom 10%",
        scrub:true

    },
    x:"200",
})



var flag =0;
document.querySelector(".ri-menu-line").addEventListener("click",function(){
    if(flag===0){
        gsap.to(".layer",{
            y:"100%",
            ease: "power1.out",
        })
        gsap.to(".ri-menu-line",{
            rotation:180,
            opacity:0
        })
        gsap.to(".ri-close-line",{
            rotation:-180,
            opacity:1
        })
        flag=1;
    }
    else{
        gsap.to(".layer",{
            y:"-100%",
            ease: "power1.out",
       
        })
        gsap.to(".ri-menu-line",{
            rotation:-180,
            opacity:1
        })
        gsap.to(".ri-close-line",{
            rotation:180,
            opacity:0
        })
        flag=0;
    }
})

document.querySelector(".Home").addEventListener("mouseover",function(){
    gsap.to(".Home>h1:nth-child(1)",{
        y:"-120"
    })
    gsap.to(".Home>h1:nth-child(2)",{
        y:"-150"
    })
})
document.querySelector(".Home").addEventListener("mouseout",function(){
    gsap.to(".Home>h1:nth-child(1)",{
        y:"0"
    })
    gsap.to(".Home>h1:nth-child(2)",{
        y:"0"
    })
})

document.querySelector(".Work").addEventListener("mouseover",function(){
    gsap.to(".Work>h1:nth-child(1)",{
        y:"-120"
    })
    gsap.to(".Work>h1:nth-child(2)",{
        y:"-150"
    })
})
document.querySelector(".Work").addEventListener("mouseout",function(){
    gsap.to(".Work>h1:nth-child(1)",{
        y:"0"
    })
    gsap.to(".Work>h1:nth-child(2)",{
        y:"0"
    })
})

document.querySelector(".About").addEventListener("mouseover",function(){
    gsap.to(".About>h1:nth-child(1)",{
        y:"-120"
    })
    gsap.to(".About>h1:nth-child(2)",{
        y:"-150"
    })
})
document.querySelector(".About").addEventListener("mouseout",function(){
    gsap.to(".About>h1:nth-child(1)",{
        y:"0"
    })
    gsap.to(".About>h1:nth-child(2)",{
        y:"0"
    })
})
document.querySelector(".Hire").addEventListener("mouseover",function(){
    gsap.to(".Hire>h1:nth-child(1)",{
        y:"-120"
    })
    gsap.to(".Hire>h1:nth-child(2)",{
        y:"-150"
    })
})
document.querySelector(".Hire").addEventListener("mouseout",function(){
    gsap.to(".Hire>h1:nth-child(1)",{
        y:"0"
    })
    gsap.to(".Hire>h1:nth-child(2)",{
        y:"0"
    })
})
